export const LTE_CATEGORIES = [
  "Anti-Wrinkle Treatments",
  "Dermal Fillers",
  "Fat Dissolving",
  "PRP & Exosomes",
  "Vitamin Injections",
  "IV Drips",
  "Skin Boosters",
  "Combination Treatments",
  "Biostimulators",
];

export const LTE_SERVICES = [
  {
    category: "Anti-Wrinkle Treatments",
    name: "3 Areas",
    price: 260,
    duration_minutes: 30,
    color: "violet",
  },
  {
    category: "Anti-Wrinkle Treatments",
    name: "Nefertiti Neck Lift",
    price: 260,
    duration_minutes: 45,
    color: "violet",
  },
  {
    category: "Anti-Wrinkle Treatments",
    name: "Jaw Relaxing/Slimming",
    price: 260,
    duration_minutes: 45,
    color: "violet",
  },
  {
    category: "Anti-Wrinkle Treatments",
    name: "Trap Tox",
    price: 320,
    duration_minutes: 45,
    color: "violet",
  },
  {
    category: "Dermal Fillers",
    name: "Lip Augmentation",
    price: 190,
    duration_minutes: 45,
    color: "rose",
  },
  {
    category: "Dermal Fillers",
    name: "Temples",
    price: 270,
    duration_minutes: 60,
    color: "rose",
  },
  {
    category: "Dermal Fillers",
    name: "8 Point Face Lift",
    price: 660,
    duration_minutes: 90,
    color: "rose",
  },
  {
    category: "Dermal Fillers",
    name: "Tear Trough",
    price: 260,
    duration_minutes: 45,
    color: "rose",
  },
  {
    category: "Dermal Fillers",
    name: "Cheeks Jawline Chin",
    price: 240,
    duration_minutes: 60,
    color: "rose",
  },
  {
    category: "Fat Dissolving",
    name: "Small Area",
    price: 160,
    duration_minutes: 45,
    color: "amber",
  },
  {
    category: "Fat Dissolving",
    name: "Large Area",
    price: 260,
    duration_minutes: 60,
    color: "amber",
  },
  {
    category: "PRP & Exosomes",
    name: "PRP Single Session",
    price: 260,
    duration_minutes: 60,
    color: "blue",
  },
  {
    category: "PRP & Exosomes",
    name: "PRP 4 Sessions",
    price: 800,
    duration_minutes: 60,
    color: "blue",
  },
  {
    category: "Vitamin Injections",
    name: "Vitamin B12",
    price: 40,
    duration_minutes: 15,
    color: "green",
  },
  {
    category: "Vitamin Injections",
    name: "Vitamin D",
    price: 60,
    duration_minutes: 15,
    color: "green",
  },
  {
    category: "IV Drips",
    name: "Total Hydration",
    price: 180,
    duration_minutes: 60,
    color: "slate",
  },
  {
    category: "IV Drips",
    name: "Detox",
    price: 180,
    duration_minutes: 60,
    color: "slate",
  },
  {
    category: "Skin Boosters",
    name: "Profhilo",
    price: 260,
    duration_minutes: 45,
    color: "blue",
  },
  {
    category: "Skin Boosters",
    name: "Sunekos",
    price: 260,
    duration_minutes: 45,
    color: "blue",
  },
  {
    category: "Combination Treatments",
    name: "Lip Filler & Lip Flip",
    price: 250,
    duration_minutes: 60,
    color: "rose",
  },
  {
    category: "Biostimulators",
    name: "Radiesse",
    price: 400,
    duration_minutes: 60,
    color: "amber",
  },
  {
    category: "Anti-Wrinkle Treatments",
    name: "Additional Areas",
    price: 60,
    duration_minutes: 15,
    color: "violet",
  },
  {
    category: "Anti-Wrinkle Treatments",
    name: "Anti-Sweating Hands / Underarms",
    price: 360,
    duration_minutes: 45,
    color: "violet",
  },
  {
    category: "Anti-Wrinkle Treatments",
    name: "Migraine Prevention",
    price: 480,
    duration_minutes: 60,
    color: "violet",
  },
  {
    category: "Dermal Fillers",
    name: "Rhinoplasty",
    price: 270,
    duration_minutes: 60,
    color: "rose",
  },
  {
    category: "PRP & Exosomes",
    name: "PRP 6 Sessions",
    price: 1100,
    duration_minutes: 60,
    color: "blue",
  },
  {
    category: "Vitamin Injections",
    name: "Vitamin C",
    price: 60,
    duration_minutes: 15,
    color: "green",
  },
  {
    category: "Vitamin Injections",
    name: "Glutathione",
    price: 150,
    duration_minutes: 30,
    color: "green",
  },
  {
    category: "Vitamin Injections",
    name: "Biotin",
    price: 60,
    duration_minutes: 15,
    color: "green",
  },
  {
    category: "IV Drips",
    name: "Wellness Plus",
    price: 180,
    duration_minutes: 60,
    color: "slate",
  },
  {
    category: "IV Drips",
    name: "Advanced Anti-Ageing",
    price: 220,
    duration_minutes: 75,
    color: "slate",
  },
  {
    category: "IV Drips",
    name: "Skin Lightening & Brightening",
    price: 220,
    duration_minutes: 75,
    color: "slate",
  },
  {
    category: "IV Drips",
    name: "Methylene Blue",
    price: 320,
    duration_minutes: 90,
    color: "slate",
  },
  {
    category: "IV Drips",
    name: "NAD+",
    price: 390,
    duration_minutes: 120,
    color: "slate",
  },
  {
    category: "Combination Treatments",
    name: "3 Areas Botox & Skin Booster",
    price: 399,
    duration_minutes: 75,
    color: "rose",
  },
  {
    category: "Combination Treatments",
    name: "NCTF Eye Brightening - 1 Session",
    price: 250,
    duration_minutes: 45,
    color: "rose",
  },
  {
    category: "Combination Treatments",
    name: "NCTF Eye Brightening - 3 Sessions",
    price: 600,
    duration_minutes: 45,
    color: "rose",
  },
  {
    category: "Skin Boosters",
    name: "Jalupro",
    price: 240,
    duration_minutes: 45,
    color: "blue",
  },
  {
    category: "Skin Boosters",
    name: "NCTF",
    price: 180,
    duration_minutes: 45,
    color: "blue",
  },
  {
    category: "Biostimulators",
    name: "Aculptra",
    price: 380,
    duration_minutes: 60,
    color: "amber",
  },
  {
    category: "Facials",
    name: "Hydra Facial Bronze",
    price: 80,
    duration_minutes: 60,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Hydra Facial Silver",
    price: 90,
    duration_minutes: 60,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Hydra Facial Gold",
    price: 150,
    duration_minutes: 75,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Hydra Facial Platinum",
    price: 220,
    duration_minutes: 90,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Laser Carbon Peel Face",
    price: 220,
    duration_minutes: 60,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Laser Carbon Peel Back",
    price: 220,
    duration_minutes: 75,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Chemical Peel Mild",
    price: 75,
    duration_minutes: 45,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Chemical Peel Medium",
    price: 100,
    duration_minutes: 60,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Chemical Peel Deep",
    price: 140,
    duration_minutes: 75,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Microdermabrasion",
    price: 35,
    duration_minutes: 30,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Radiofrequency Skin Tightening",
    price: 30,
    duration_minutes: 30,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "Microneedling",
    price: 150,
    duration_minutes: 60,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "PRP Hair",
    price: 175,
    duration_minutes: 60,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "PRP Face",
    price: 175,
    duration_minutes: 60,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "PRP Lips",
    price: 150,
    duration_minutes: 45,
    color: "cyan",
  },
  {
    category: "Facials",
    name: "PRP with Microneedling",
    price: 250,
    duration_minutes: 75,
    color: "cyan",
  },
  {
    category: "Laser Hair Removal",
    name: "Upper Lip",
    price: 29,
    duration_minutes: 15,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Chin",
    price: 30,
    duration_minutes: 15,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Chest",
    price: 30,
    duration_minutes: 20,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Stomach",
    price: 35,
    duration_minutes: 20,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Half Arm",
    price: 75,
    duration_minutes: 30,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Half Leg",
    price: 80,
    duration_minutes: 30,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Underarm",
    price: 99,
    duration_minutes: 20,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Bikini",
    price: 120,
    duration_minutes: 30,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Full Face",
    price: 120,
    duration_minutes: 30,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Full Arm",
    price: 150,
    duration_minutes: 45,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Full Leg",
    price: 160,
    duration_minutes: 60,
    color: "pink",
  },
  {
    category: "Laser Hair Removal",
    name: "Full Body",
    price: 299,
    duration_minutes: 120,
    color: "pink",
  },
  {
    category: "Massage Therapy",
    name: "Relaxing Massage 30 Min",
    price: 70,
    duration_minutes: 30,
    color: "emerald",
  },
  {
    category: "Massage Therapy",
    name: "Relaxing Massage 60 Min",
    price: 100,
    duration_minutes: 60,
    color: "emerald",
  },
  {
    category: "Massage Therapy",
    name: "Hot Stone Massage 60 Min",
    price: 80,
    duration_minutes: 60,
    color: "emerald",
  },
  ];
